In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
df=pd.read_csv("bank_churn_dataset.csv")
df.head()

,id,full_name,credit_sco,gender,age,occupation,balance,monthly_ir,address,origin_province,...,last_transaction_month,created_date,exit,customer_segment,engagement_score,loyalty_level,digital_behavior,risk_score,risk_segment,cluster_group
0,1,Đặng Văn Vũ,725,male,55,Chủ Doanh nghiệp nhỏ,177306004,121000000,Phường An Hội (BT),TP. Hồ Chí Minh,...,91038993,27/02/2025,False,Priority,90,Bronze,mobile,0.0359,Low,4
1,2,Bùi Hữu Phúc,689,male,45,Nội trợ/Sinh viên,1927416,5000000,Phường Bến Thành (Q1),Đồng Nai,...,3255569,29/07/2021,False,Mass,63,Gold,mobile,0.2664,Low,2
2,3,Lê Văn Mai,702,female,44,Chủ Doanh nghiệp nhỏ,304931745,109000000,Phường Hòa Bình (Q11),TP. Hồ Chí Minh,...,0,03/03/2021,False,Priority,36,Silver,offline,0.1343,Low,4
3,4,Dương Trần Nhiên,766,male,44,Chủ Doanh nghiệp nhỏ,50615501,79000000,Phường 7 (Q7),TP. Hồ Chí Minh,...,0,12/02/2022,False,Priority,23,Bronze,offline,0.2185,Low,4
4,5,Dương Thu Linh,677,female,77,Giáo viên/Giảng viên,40532432,25000000,Phường Thắng Lợi (Q10),TP. Hồ Chí Minh,...,0,24/07/2022,False,Emerging,23,Bronze,offline,0.2942,Low,2

In [3]:
df.tail()

,id,full_name,credit_sco,gender,age,occupation,balance,monthly_ir,address,origin_province,...,last_transaction_month,created_date,exit,customer_segment,engagement_score,loyalty_level,digital_behavior,risk_score,risk_segment,cluster_group
79995,79996,Dương Anh Chi,682,female,38,Nhân viên văn phòng/Công chức,191593897,18000000,Phường Tân Định (Q1),TP. Hồ Chí Minh,...,0,17/09/2021,False,Affluent,10,Bronze,offline,0.3094,Low,2
79996,79997,Vũ Thu Ánh,710,female,44,Nhân viên văn phòng/Công chức,169955694,29000000,Phường Bến Thành (Q1),Đồng Nai,...,0,29/03/2022,False,Affluent,22,Bronze,offline,0.2209,Low,2
79997,79998,Lê Quang Huy,701,male,62,Kinh doanh/Bán hàng,148475041,31000000,Phường Tân Định (Q1),TP. Hồ Chí Minh,...,213134296,27/03/2022,False,Emerging,68,Gold,mobile,0.1510,Low,3
79998,79999,Hoàng Thanh Châu,619,male,49,Nội trợ/Sinh viên,95040840,12000000,Phường Hòa Bình (Q11),TP. Hồ Chí Minh,...,0,29/03/2021,False,Emerging,14,Bronze,offline,0.3804,Low,2
79999,80000,Bùi Anh Yến,800,female,56,Quản lý/Lãnh đạo,363171524,136000000,Xã Xuân Thới Đông (HM),TP. Hồ Chí Minh,...,0,14/11/2021,False,Priority,34,Bronze,offline,0.1697,Low,4

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 80000
Columns: 26

In [5]:
print(df.columns)

Index(['id', 'full_name', 'credit_sco', 'gender', 'age', 'occupation',
       'balance', 'monthly_ir', 'address', 'origin_province', 'tenure_ye',
       'married', 'nums_card', 'nums_service', 'active_member',
       'last_active_date', 'last_transaction_month', 'created_date', 'exit',
       'customer_segment', 'engagement_score', 'loyalty_level',
       'digital_behavior', 'risk_score', 'risk_segment', 'cluster_group'],
      dtype='object')

In [6]:
df.info

<bound method DataFrame.info of           id         full_name  credit_sco  gender  age  \
0          1       Đặng Văn Vũ         725    male   55
1          2      Bùi Hữu Phúc         689    male   45
2          3        Lê Văn Mai         702  female   44
3          4  Dương Trần Nhiên         766    male   44
4          5    Dương Thu Linh         677  female   77
...      ...               ...         ...     ...  ...
79995  79996     Dương Anh Chi         682  female   38
79996  79997        Vũ Thu Ánh         710  female   44
79997  79998      Lê Quang Huy         701    male   62
79998  79999  Hoàng Thanh Châu         619    male   49
79999  80000       Bùi Anh Yến         800  female   56

                          occupation    balance  monthly_ir  \
0               Chủ Doanh nghiệp nhỏ  177306004   121000000
1                  Nội trợ/Sinh viên    1927416     5000000
2               Chủ Doanh nghiệp nhỏ  304931745   109000000
3               Chủ Doanh nghiệp nhỏ   50615501    79000000
4               Giáo viên/Giảng viên   40532432    25000000
...                              ...        ...         ...
79995  Nhân viên văn phòng/Công chức  191593897    18000000
79996  Nhân viên văn phòng/Công chức  169955694    29000000
79997            Kinh doanh/Bán hàng  148475041    31000000
79998              Nội trợ/Sinh viên   95040840    12000000
79999               Quản lý/Lãnh đạo  363171524   136000000

                      address  origin_province  ...  last_transaction_month  \
0          Phường An Hội (BT)  TP. Hồ Chí Minh  ...                91038993
1       Phường Bến Thành (Q1)         Đồng Nai  ...                 3255569
2       Phường Hòa Bình (Q11)  TP. Hồ Chí Minh  ...                       0
3               Phường 7 (Q7)  TP. Hồ Chí Minh  ...                       0
4      Phường Thắng Lợi (Q10)  TP. Hồ Chí Minh  ...                       0
...                       ...              ...  ...                     ...
79995    Phường Tân Định (Q1)  TP. Hồ Chí Minh  ...                       0
79996   Phường Bến Thành (Q1)         Đồng Nai  ...                       0
79997    Phường Tân Định (Q1)  TP. Hồ Chí Minh  ...               213134296
79998   Phường Hòa Bình (Q11)  TP. Hồ Chí Minh  ...                       0
79999  Xã Xuân Thới Đông (HM)  TP. Hồ Chí Minh  ...                       0

       created_date   exit  customer_segment  engagement_score loyalty_level  \
0        27/02/2025  False          Priority                90        Bronze
1        29/07/2021  False              Mass                63          Gold
2        03/03/2021  False          Priority                36        Silver
3        12/02/2022  False          Priority                23        Bronze
4        24/07/2022  False          Emerging                23        Bronze
...             ...    ...               ...               ...           ...
79995    17/09/2021  False          Affluent                10        Bronze
79996    29/03/2022  False          Affluent                22        Bronze
79997    27/03/2022  False          Emerging                68          Gold
79998    29/03/2021  False          Emerging                14        Bronze
79999    14/11/2021  False          Priority                34        Bronze

       digital_behavior risk_score  risk_segment cluster_group
0                mobile     0.0359           Low             4
1                mobile     0.2664           Low             2
2               offline     0.1343           Low             4
3               offline     0.2185           Low             4
4               offline     0.2942           Low             2
...                 ...        ...           ...           ...
79995           offline     0.3094           Low             2
79996           offline     0.2209           Low             2
79997            mobile     0.1510           Low             3
79998           offline     0.3804           Low             2
79999           offline     0.1697           Low             4

[80000 rows x 26 columns]>

In [7]:
df.isnull().sum()

id                        0
full_name                 0
credit_sco                0
gender                    0
age                       0
occupation                0
balance                   0
monthly_ir                0
address                   0
origin_province           0
tenure_ye                 0
married                   0
nums_card                 0
nums_service              0
active_member             0
last_active_date          0
last_transaction_month    0
created_date              0
exit                      0
customer_segment          0
engagement_score          0
loyalty_level             0
digital_behavior          0
risk_score                0
risk_segment              0
cluster_group             0
dtype: int64

In [8]:
df = df.dropna()
print(df.shape)

(80000, 26)

In [9]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [11]:
df.describe(include='all')

,id,full_name,credit_sco,gender,age,occupation,balance,monthly_ir,address,origin_province,...,last_transaction_month,created_date,exit,customer_segment,engagement_score,loyalty_level,digital_behavior,risk_score,risk_segment,cluster_group
count,80000.000000,80000,80000.000000,80000,80000.000000,80000,8.000000e+04,8.000000e+04,80000,80000,...,8.000000e+04,80000,80000,80000,80000.000000,80000,80000,80000.000000,80000,80000.000000
unique,NaN,5100,NaN,2,NaN,10,NaN,NaN,16,9,...,NaN,1643,2,4,NaN,3,2,NaN,2,NaN
top,NaN,Lê Minh Quang,NaN,male,NaN,Kỹ sư/Chuyên viên IT,NaN,NaN,Linh Trung (TP Thủ Đức),TP. Hồ Chí Minh,...,NaN,09/05/2023,False,Emerging,NaN,Bronze,offline,NaN,Low,NaN
freq,NaN,42,NaN,40008,NaN,8199,NaN,NaN,5085,40148,...,NaN,76,65600,31662,NaN,69252,62824,NaN,74753,NaN
mean,40000.500000,NaN,684.321137,NaN,49.381862,NaN,6.118320e+07,3.778820e+07,NaN,NaN,...,8.831755e+06,NaN,NaN,NaN,31.725400,NaN,NaN,0.269260,NaN,1.971037
std,23094.155105,NaN,51.169733,NaN,15.067480,NaN,8.868620e+07,3.655107e+07,NaN,NaN,...,3.378683e+07,NaN,NaN,NaN,23.474862,NaN,NaN,0.091891,NaN,1.040763
min,1.000000,NaN,495.000000,NaN,20.000000,NaN,4.086630e+05,3.000000e+06,NaN,NaN,...,0.000000e+00,NaN,NaN,NaN,7.000000,NaN,NaN,0.017300,NaN,1.000000
25%,20000.750000,NaN,649.000000,NaN,38.000000,NaN,1.462592e+07,1.400000e+07,NaN,NaN,...,0.000000e+00,NaN,NaN,NaN,16.000000,NaN,NaN,0.200400,NaN,1.000000
50%,40000.500000,NaN,682.000000,NaN,47.000000,NaN,3.090276e+07,2.300000e+07,NaN,NaN,...,0.000000e+00,NaN,NaN,NaN,22.000000,NaN,NaN,0.277400,NaN,2.000000
75%,60000.250000,NaN,718.000000,NaN,58.000000,NaN,6.960994e+07,4.700000e+07,NaN,NaN,...,0.000000e+00,NaN,NaN,NaN,38.000000,NaN,NaN,0.338900,NaN,2.000000
max,80000.000000,NaN,800.000000,NaN,90.000000,NaN,1.000000e+09,2.160000e+08,NaN,NaN,...,6.000000e+08,NaN,NaN,NaN,100.000000,NaN,NaN,0.540400,NaN,4.000000

In [12]:
print(df.dtypes)

id                          int64
full_name                  object
credit_sco                  int64
gender                     object
age                         int64
occupation                 object
balance                     int64
monthly_ir                  int64
address                    object
origin_province            object
tenure_ye                   int64
married                     int64
nums_card                   int64
nums_service                int64
active_member                bool
last_active_date           object
last_transaction_month      int64
created_date               object
exit                         bool
customer_segment           object
engagement_score            int64
loyalty_level              object
digital_behavior           object
risk_score                float64
risk_segment               object
cluster_group               int64
dtype: object

In [13]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str)

In [14]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.lower()

In [15]:
df.sample(5)

,id,full_name,credit_sco,gender,age,occupation,balance,monthly_ir,address,origin_province,...,last_transaction_month,created_date,exit,customer_segment,engagement_score,loyalty_level,digital_behavior,risk_score,risk_segment,cluster_group
4230,4231,dương thị quang,686,male,37,lao động phổ thông,6166533,8000000,phường 2 (tân bình),tỉnh khác,...,0,25/01/2023,True,mass,14,bronze,offline,0.3419,low,2
29950,29951,lê thị châu,718,male,34,nhân viên văn phòng/công chức,24388936,21000000,phường vĩnh hội (q4),hà nội,...,0,15/01/2022,False,emerging,21,bronze,offline,0.2728,low,2
78838,78839,vũ thu lan,600,female,23,hưu trí,8869342,8000000,linh trung (tp thủ đức),tp. hồ chí minh,...,0,11/05/2023,True,mass,21,bronze,offline,0.4110,medium,2
39189,39190,bùi thu tùng,679,male,56,lao động phổ thông,20574684,14000000,xã vĩnh lộc a (bc),cần thơ,...,6548863,03/04/2025,False,mass,65,bronze,mobile,0.2174,low,1
73370,73371,nguyễn văn phúc,643,male,37,kinh doanh/bán hàng,49409470,18000000,phường 14 (q12),bình dương,...,0,30/03/2022,False,emerging,14,bronze,offline,0.3523,low,2

In [16]:
with open("bank_churn_dataset.pkl", "wb") as file:
    pickle.dump(df, file)

print("Pickle file saved successfully.")

Pickle file saved successfully.

In [17]:
with open("bank_churn_dataset.pkl", "rb") as file:
    data = pickle.load(file)

In [18]:
print(type(data))
print(data.shape)

<class 'pandas.core.frame.DataFrame'>
(80000, 26)